---
abstract: 'Check that a library is available for FFI'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.28'
  Test::More: '0.94'
  perl: '5.006'
configure_requires:
  Module::Build: '0.28'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-CheckLib
requires:
  perl: '5.006'
resources:
  bugtracker: https://github.com/plicease/FFI-CheckLib/issues
  homepage: http://perl.wdlabs.com/FFI-CheckLib
  repository: git://github.com/plicease/FFI-CheckLib.git
version: '0.04'
